### ISSUE TITLE
Scripts for short videos for each module

### ISSUE THREAD

**Issue by sgibson91** [martinagvilas/jupytercon_tutorial#10]
- Welcome to module X
- So far you have seen A, B, C
- In this module, you will learn X, Y, Z
- You should already have 1, 2, 3
- Learning objective are i, ii, iii

**Comment by martinagvilas** [comment]
Hey, @sgibson91 @malvikasharan I think I will use for the videos some slides with video scree-captures. If you are using slides, should we use the same template? (in terms of style) Or each of us uses whatever they prefer?

**Comment by sgibson91** [comment]
I think a recent JupyterCon email had link to a slide template

**Comment by sgibson91** [comment]
https://docs.google.com/presentation/d/187VFboD0sjwNjEmDnRTmYP0f2PeNmCBc4ibkdMpS-zw/edit?usp=sharing

**Comment by martinagvilas** [comment]
awesome, hadn't seen this, thanks!
