### ISSUE TITLE
Deadline extension: 18th Sept

### ISSUE THREAD

**Issue by sgibson91** [martinagvilas/jupytercon_tutorial#2]
The "good" news is that we now have until Sept 18th to submit our materials

**Comment by martinagvilas** [comment]
Apparently moved to the 20th now!

**Comment by sgibson91** [comment]
> Apparently moved to the 20th now!

For video recordings only

**Comment by martinagvilas** [comment]
> > Apparently moved to the 20th now!
> 
> For video recordings only

Good to know 👍
