### ISSUE TITLE
Update JupyterCon repo and test

### ISSUE THREAD

**Issue by malvikasharan** [martinagvilas/jupytercon_tutorial#23]
After #22 is done, we can update the JupyterCon repo: https://github.com/jupytercon/jupyterbook-with-turing-way

**Comment by malvikasharan** [comment]
Are we ready to copy this under the JupyterCon organisation repo? After I have the video from Kirstie, I will share that with Tania, along with the repo and details they have requested (updated on the README).

**Comment by martinagvilas** [comment]
I think we are! I'm still trying to figure out if we can use Binder, and there is also the issue that @sgibson91 mentioned about creating a `gh-pages` branch, but we can keep editing these minor things directly to that repository right?

**Comment by malvikasharan** [comment]
For the last bits I have added a CoC and contribution guideline. I will and upload our presentations and create a PR. Once these are merged, I can send a PR there.

**Comment by malvikasharan** [comment]
Is there a way to send PR across different repo? How can we share files across different repo while not losing the history?

**Comment by malvikasharan** [comment]
Yay! Merging this repo with the one on JupyterCon worked. I used the instructions described here: https://stackoverflow.com/questions/1425892/how-do-you-merge-two-git-repositories.
